In [1]:
# Exercice 2 

# Q1

liste_revenus = [1800, 1500, 2200, 3000, 2172, 5000, 1400, 1200, 1100, 1300]
liste_noms = ['Ava', 'Bob', 'Cao', 'Dan', 'Eli', 'Fay', 'Guy', 'Hue', 'Ian', 'Joy']

import numpy as np

revenus = np.array(liste_revenus)
noms = np.array(liste_noms)

print(revenus)

hauts_revenus = revenus[revenus > 2000]

print(noms[revenus > 2000])
print(hauts_revenus)

print(np.average(revenus))

print(np.round(np.sum(revenus), -3))

revenus[revenus == 1100] += 150
revenus[noms == 'Ava'] += 100

print(revenus)

[1800 1500 2200 3000 2172 5000 1400 1200 1100 1300]
['Cao' 'Dan' 'Eli' 'Fay']
[2200 3000 2172 5000]
2067.2
21000
[1900 1500 2200 3000 2172 5000 1400 1200 1250 1300]


In [2]:
# Q2
ava = [1800, 21, 0]
bob = [1500, 54, 2]
cao = [2200, 28, 3]
dan = [3000, 37, 1]
eli = [2172, 37, 2]
fay = [5000, 32, 0]
guy = [1400, 23, 0]
hue = [1200, 25, 1]
ian = [1100, 19, 0]
joy = [1300, 31, 2]
liste_clients = [ava, bob, cao, dan, eli, fay, guy, hue, ian, joy]
liste_noms = ['Ava', 'Bob', 'Cao', 'Dan', 'Eli', 'Fay', 'Guy', 'Hue', 'Ian', 'Joy']

clients = np.array(liste_clients)
noms = np.array(liste_noms)

cao_from_array = clients[noms == 'Cao']
print(cao_from_array[0][0] * 0.35)

kim = [1900, 31, 1]
clients = np.append(clients, [kim], axis=0)
noms = np.append(noms, 'Kim')

print(clients)
print(noms)

clients_age = clients[:,1]

print(clients_age)


770.0
[[1800   21    0]
 [1500   54    2]
 [2200   28    3]
 [3000   37    1]
 [2172   37    2]
 [5000   32    0]
 [1400   23    0]
 [1200   25    1]
 [1100   19    0]
 [1300   31    2]
 [1900   31    1]]
['Ava' 'Bob' 'Cao' 'Dan' 'Eli' 'Fay' 'Guy' 'Hue' 'Ian' 'Joy' 'Kim']
[21 54 28 37 37 32 23 25 19 31 31]


In [19]:
# Exercice 3

# Q1

v1 = np.arange(1, 20, 2)

print(v1)

rng = np.random.default_rng()
v2 = rng.integers(low=25, high=70, size=10)

print(v2)

concatenated = np.concatenate((v1, v2))

print(concatenated)

split = np.reshape(concatenated, (4, 5))

print(split)

v1v2_rw = np.stack((v1, v2), axis=0)

print(v1v2_rw)

v1v2_cw = np.stack((v1, v2), axis=1)

print(v1v2_cw)

v1v2_cw = np.column_stack((np.arange(0, len(v1v2_cw), 1) , v1v2_cw))

print(v1v2_cw)

[ 1  3  5  7  9 11 13 15 17 19]
[47 30 46 35 57 37 49 35 38 38]
[ 1  3  5  7  9 11 13 15 17 19 47 30 46 35 57 37 49 35 38 38]
[[ 1  3  5  7  9]
 [11 13 15 17 19]
 [47 30 46 35 57]
 [37 49 35 38 38]]
[[ 1  3  5  7  9 11 13 15 17 19]
 [47 30 46 35 57 37 49 35 38 38]]
[[ 1 47]
 [ 3 30]
 [ 5 46]
 [ 7 35]
 [ 9 57]
 [11 37]
 [13 49]
 [15 35]
 [17 38]
 [19 38]]
[[ 0  1 47]
 [ 1  3 30]
 [ 2  5 46]
 [ 3  7 35]
 [ 4  9 57]
 [ 5 11 37]
 [ 6 13 49]
 [ 7 15 35]
 [ 8 17 38]
 [ 9 19 38]]


In [40]:
# Q2

A = np.array([
	[1, 2], 
	[3, 4]])
B = np.array([
	[5, 10, 2], 
	[15, 7, 20]])

a_plat = np.concatenate((A.flatten(), B.flatten()))

print(a_plat)

np.random.shuffle(a_plat)

print(a_plat)
print(np.argmin(a_plat))
print(np.argmax(a_plat))

C = np.random.randint(10, size=(5, 3)) 

print(C)
print(np.argmin(C, axis=0))
print(np.argmax(C, axis=0))

print(np.transpose(a_plat))
print(np.transpose(C))


[ 1  2  3  4  5 10  2 15  7 20]
[15  2  7  4  1  2 10 20  3  5]
4
7
[[1 9 2]
 [3 2 4]
 [8 2 9]
 [2 6 9]
 [1 6 4]]
[0 1 0]
[2 0 2]
[15  2  7  4  1  2 10 20  3  5]
[[1 3 8 2 1]
 [9 2 2 6 6]
 [2 4 9 9 4]]


In [102]:
# Q3

A = np.array([
[1, 2, 3],
[1, 2, 3],
[4, 5, 6],
[1, 1, 1],
[7, 8, 9],
[1, 2, 3],
[10, 10, 10],
[1, 1, 1],
[14, 15, 16],
[1, 2, 3]
])

first = A[0]
lines_that_differ_from_first_line = A[(A[:,0] != A[0,0]) | (A[:,1] != A[0,1]) | (A[:,2] != A[0,2])]

print(lines_that_differ_from_first_line)

without_duplicates = np.unique(A, axis=0)

# print(without_duplicates)

B = np.random.randint(2, size=A.shape)


C = np.where(B > 0, A, -A)

print(C)

C[[0, len(C) - 1]] = C[[len(C) - 1, 0]]

print(C)



[[ 4  5  6]
 [ 1  1  1]
 [ 7  8  9]
 [10 10 10]
 [ 1  1  1]
 [14 15 16]]
[[  1   2  -3]
 [  1  -2  -3]
 [  4   5  -6]
 [ -1  -1   1]
 [ -7   8  -9]
 [  1   2   3]
 [-10 -10 -10]
 [  1  -1   1]
 [-14 -15 -16]
 [ -1  -2   3]]
[[ -1  -2   3]
 [  1  -2  -3]
 [  4   5  -6]
 [ -1  -1   1]
 [ -7   8  -9]
 [  1   2   3]
 [-10 -10 -10]
 [  1  -1   1]
 [-14 -15 -16]
 [  1   2  -3]]
